# Generated by Django 4.1.6 on 2023-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Videographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2555)),
                ('speciality', models.CharField(max_length=255)),
            ],
        ),
    ]
