# Generated by Django 4.1.6 on 2023-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='videographer',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='videographer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videographer',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_location',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='country',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='speciality',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
